version: "3.9"

services:

  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: company_employees
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: employee_app
    depends_on:
      - postgres
    ports:
      - "8090:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: company_employees
      DB_USER: app
      DB_PASSWORD: app123

volumes:
  pgdata:
