apiVersion: v1
kind: Service
metadata:
  name: employee-management
  namespace: default
  labels:
    app: employee-management
spec:
  type: ClusterIP
  selector:
    app: employee-management
  ports:
    - name: http
      port: 80
      targetPort: 8080
