grafana:
  adminUser: admin
  adminPassword: admin
  initChownData:
    enabled: false
  persistence:
    enabled: true
    type: pvc
    accessModes:
      - ReadWriteOnce
    size: 5Gi
    finalizers:
      - kubernetes.io/pvc-protection

prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 8Gi

    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}

alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate: null